### ISSUE TITLE
Error getting default ItemStack

### ISSUE THREAD

**Issue by GMatrixGames** [BGHDDevelopment/LiteBansGUI#1]
Hello,

I am running 1.12.2 latest and I get this [stacktrace](https://hasteb.in/yagajoqe.rb) on running the command /punish. It's trying to get the item of BOOK_AND_QUILL, but it's a material in the JavaDocs of Spigot 1.12.2.

**Comment by BGHDDevelopment** [comment]
The book and quill was changed according to the ID to WRITABLE_BOOK.

Also, make sure you are on the newest version.

I will fix any issues that you find. If you have discord feel free to join the support chat: https://discord.gg/hYkvkeu
